/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package1;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kompik1
 */
public class Okno_W extends javax.swing.JFrame {

    /**
     * Creates new form Okno_W
     */
    public Okno_W() {
        initComponents();
        setVisible(true);
        lacz();
        //wstaw();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnWstaw = new javax.swing.JButton();
        jBtnCofnij = new javax.swing.JButton();
        jTFtemperatura = new javax.swing.JTextField();
        jTFwilgotnosc = new javax.swing.JTextField();
        jTFcisnienie = new javax.swing.JTextField();
        jTFwiatr = new javax.swing.JTextField();
        jTFdata = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Temperatura");

        jLabel2.setText("Wilgotność ");

        jLabel3.setText("Ciśnienie ");

        jLabel4.setText("Wiatr");

        jLabel5.setText("Data");

        jBtnWstaw.setText("Wstaw");
        jBtnWstaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnWstawMouseClicked(evt);
            }
        });

        jBtnCofnij.setText("Cofnij");
        jBtnCofnij.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCofnijMouseClicked(evt);
            }
        });

        jTFtemperatura.setMinimumSize(new java.awt.Dimension(50, 20));
        jTFtemperatura.setPreferredSize(new java.awt.Dimension(50, 20));

        jTFwilgotnosc.setMinimumSize(new java.awt.Dimension(50, 20));
        jTFwilgotnosc.setPreferredSize(new java.awt.Dimension(50, 20));
        jTFwilgotnosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFwilgotnoscActionPerformed(evt);
            }
        });

        jTFcisnienie.setPreferredSize(new java.awt.Dimension(50, 20));

        jTFwiatr.setText("km/h KK");
        jTFwiatr.setPreferredSize(new java.awt.Dimension(50, 20));

        jTFdata.setText("YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFwiatr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFdata, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jTFtemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFwilgotnosc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcisnienie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jBtnWstaw)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCofnij)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTFtemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFwilgotnosc, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTFcisnienie, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jTFwiatr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnWstaw)
                    .addComponent(jBtnCofnij))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnWstawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnWstawMouseClicked
        String temperatura = jTFtemperatura.getText();
        String wilgotnosc = jTFwilgotnosc.getText();
        String cisnienie = jTFcisnienie.getText();
        String wiatr = jTFwiatr.getText();
        String data = jTFdata.getText();       
        
        
        try {
            LaczenieZBaza lz = new LaczenieZBaza();
            String q = "Insert into Dane ( temperatura, wilgotnosc, cisnienie, wiatr, data)" +  "values ("+ temperatura +","+ wilgotnosc +","+ cisnienie +",'"+ wiatr +"','"+ data +"' )";
            lz.insertDoBazy(q);
            System.out.println("wstawiono!");
            powrot();
        } catch (SQLException ex) {
            Logger.getLogger(Okno_W.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnWstawMouseClicked

    private void jTFwilgotnoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFwilgotnoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFwilgotnoscActionPerformed

    private void jBtnCofnijMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCofnijMouseClicked
        powrot();
        // Logger.getLogger(Okno_W.class.getName()).log(Level.SEVERE, null, ex);       
    }//GEN-LAST:event_jBtnCofnijMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno_W().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCofnij;
    private javax.swing.JButton jBtnWstaw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTFcisnienie;
    private javax.swing.JTextField jTFdata;
    private javax.swing.JTextField jTFtemperatura;
    private javax.swing.JTextField jTFwiatr;
    private javax.swing.JTextField jTFwilgotnosc;
    // End of variables declaration//GEN-END:variables

    private void lacz(){
        try{
            LaczenieZBaza lz = new LaczenieZBaza();
            lz.selectZBazy("Select * from Dane", 6);
        } catch(SQLException ex)
        {
            
        }
        
        
    }
    
     private void wstaw(){
        try{
            LaczenieZBaza lz = new LaczenieZBaza();
            //String q = "Insert into Dane values (null,'" + 23 + "','" + 10 + "'," +  1000 + "','" + 30km/h  NE  + "','" + 2019-06-03 + ")";
            String q = "Insert into Dane (id, temperatura, wilgotnosc, cisnienie, wiatr, data)" +  "values ('5', '23', '10',' 1000', '30km/h  NE', '2019-06-03')";
            lz.insertDoBazy(q);
            // Statement s = lz.getSt();
            //s.executeUpdate("INSERT INTO Dane(temperatura, wilgotnosc, cisnienie, wiatr, data)" + "VALUES (null, null, null, null, null)");
            System.out.println("wstawiono");
        }catch(SQLException ex){
            
        }
        
        
        
    }
     
     private void powrot() 
     {
         setVisible(false);
         try{
            new Okno_G();
         } catch(SQLException ex){
             
         }         
     }
    
}
